---
- name: Setup Topology Bootstrap
  hosts: topology_bootstrap
  vars:
    mode: "bootstrap"
    docker_port: "6960"
  roles:
    - "../roles/common"
    - "../roles/topology-node"

- name: Setup Topology Node
  hosts: topology_node
  vars:
    mode: "node"
    docker_port: "69{{ inventory_hostname.replace('node', '').replace('.topology.gg', '') }}"
  roles:
    - "../roles/common"
    - "../roles/topology-node"
