---
- name: Setup Topology Bootstrap
  hosts: topology_bootstrap
  vars:
    mode: "bootstrap"
    docker_port: "6960"
  roles:
    - "../roles/common"
    - "../roles/topology-node"

#- name: Setup Topology Node
#  hosts: topology_node
#  vars:
#    mode: "node"
#    docker_port: '69{{ inventory_hostname | regex_replace(".*\D(\d+).*", "\1") }}'
#  roles:
#    - "../roles/common"
#    - "../roles/topology-node"

- name: Setup proxy
  hosts: topology_bootstrap
  vars:
    sites:
      "{{ inventory_hostname }}=http://172.17.0.1:50000"
      # ;{{ groups["topology_node"]
      #   | map("regex_replace", "(.*\D)(\d+)(.*)", "\1\2\3=http://172.17.0.1:69\2")
      #   | list
      #   | join(";")
      # }}"
  roles:
    - "../roles/proxy"
