---
- name: Bootstrap Topchain Nodes with Ignite Toolchain
  hosts: topchain_node
  become: yes

  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64

  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Include Docker installation role if not installed
      ansible.builtin.include_role:
        name: install-docker
      when: docker_installed.failed

    # Install additional required packages for Topchain node setup
    - name: Install additional required packages for Topchain node setup
      ansible.builtin.apt:
        name:
          - git
          - make
        state: present

    - name: Start a Topchain node
      ansible.builtin.include_role:
        name: topchain-node
