---
- name: Ensures host directory exists
  file:
    path: /opt/topology/hosts/{{ inventory_hostname }}
    state: directory

- name: Generate private key seed
  community.crypto.openssh_keypair:
    path: /opt/topology/hosts/{{ inventory_hostname }}/key_seed

- name: Read the private key seed content directly
  shell: "sed -n '2p' /opt/topology/hosts/{{ inventory_hostname }}/key_seed | head -c 32"
  register: private_key_seed

- name: Create .env file with environment variables
  copy:
    dest: /opt/topology/hosts/{{ inventory_hostname }}/.env
    content: |
      ADDRESSES=/ip4/0.0.0.0/tcp/50000/ws,/ip4/0.0.0.0/tcp/50001
      PRIVATE_KEY_SEED={{ private_key_seed.stdout }}

- name: Add bootstrap flag
  lineinfile:
    path: /opt/topology/hosts/{{ inventory_hostname }}/.env
    line: |
      BOOTSTRAP=true
      BOOTSTRAP_PEERS=[]
    create: yes
  when: "'topology_bootstrap' in group_names"

- name: Add composer file
  template:
    src: docker-compose.yaml.j2
    dest: /opt/topology/hosts/{{ inventory_hostname }}/docker-compose.yaml

- name: Run topology on docker
  community.docker.docker_compose_v2:
    state: present
    pull: always
    project_src: /opt/topology/hosts/{{ inventory_hostname }}
    files:
      - docker-compose.yaml
